sudo: required
dist: trusty
language: generic
services:
  - docker

script:
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then ./images/php7-fpm-trusty64/update_image.sh ; fi

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then ./images/php7-fpm-trusty64/update_image.sh --deploy ; fi

