---

- name: Update APT
  apt: update_cache=yes


- name: Upgrade APT
  apt: upgrade=yes


- name: Install usual packages
  action: apt name="{{ item }}" state=latest update_cache=true
  with_items:
    - dstat
    - joe
    - git
    - xz-utils
    - python-software-properties
    - ant
    - curl

